export const GET_TOKEN_FROM_STORAGE = 'GET_TOKEN_FROM_STORAGE';
//  Sign In
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
//  Sign Up
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
//  Sign Out
export const SIGN_OUT_START = 'SIGN_OUT_START';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
// Get Items
export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';
//  Get Liked / Disliked Items
export const GET_SCORED_ITEMS_START = 'GET_SCORED_ITEMS_START';
export const GET_SCORED_ITEMS_SUCCESS = 'GET_SCORED_ITEMS_SUCCESS';
export const GET_SCORED_ITEMS_FAILURE = 'GET_SCORED_ITEMS_FAILURE';
export const UPDATE_SCORED_ITEMS = 'UPDATE_SCORED_ITEMS';
export const CLEAN_UP_ITEMS = 'CLEAN_UP_ITEMS';
export const SET_IF_UPDATED='SET_IF_UPDATED'
