export const GET_TOKEN_FROM_STORAGE = "GET_TOKEN_FROM_STORAGE";
//  Sign In
export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
//  Sign Up
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
//  Sign Out
export const SIGN_OUT_START = "SIGN_OUT_START";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
// Get Items
export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAILURE = "GET_ITEMS_FAILURE";
//  Get Liked / Disliked Items
export const GET_SCORED_ITEMS_START = "GET_SCORED_ITEMS_START";
export const GET_SCORED_ITEMS_SUCCESS = "GET_SCORED_ITEMS_SUCCESS";
export const GET_SCORED_ITEMS_FAILURE = "GET_SCORED_ITEMS_FAILURE";
export const UPDATE_SCORED_ITEMS = "UPDATE_SCORED_ITEMS";
export const CLEAN_UP_ITEMS = "CLEAN_UP_ITEMS";
export const SET_IF_UPDATED = "SET_IF_UPDATED";
//  Search for Items
export const SEARCH_ITEMS_START = "SEARCH_ITEMS_START";
export const SEARCH_ITEMS_SUCCESS = "SEARCH_ITEMS_SUCCESS";
export const SEARCH_ITEMS_FAILURE = "SEARCH_ITEMS_FAILURE";
//  Search and filter
export const SEARCH_AND_FILTER_START = "SEARCH_AND_FILTER_START";
export const SEARCH_AND_FILTER_SUCCESS = "SEARCH_AND_FILTER_SUCCESS";
export const SEARCH_AND_FILTER_FAILURE = "SEARCH_AND_FILTER_FAILURE";
//  Get Item
export const GET_ITEM = "GET_ITEM";
//  Update Item View Count
export const UPDATE_IVC_START = "UPDATE_IVC_START";
export const UPDATE_IVC_SUCCESS = "UPDATE_IVC_SUCCESS";
export const UPDATE_IVC_FAILURE = "UPDATE_IVC_FAILURE";
//  Get User Profile
export const GET_USER_PROFILE_START = "GET_USER_PROFILE_START";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCSESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";
//  Cart Items
export const GET_CART_ITEMS = "GET_CART_ITEMS";
// Add to Cart
export const ADD_TO_CART = "ADD_TO_CART";
//  Clear Cart
export const CLEAR_CART = "CLEAR_CART";
