export const GET_TOKEN_FROM_STORAGE = 'GET_TOKEN_FROM_STORAGE';
//  Log In
export const SIGN_IN_START = 'SIGN_IN_START';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
